### ISSUE TITLE
"pfile"/"patchup file": ignored when using tssmokeperl.pl?

### ISSUE THREAD

**Issue by bram-perl** [abeltje/Test-Smoke#56]
The configuration contains a `pfile` ("patchup file") option which is described as:

    C<pfile> is the path to a textfile that holds the names of patches to
    be applied before smoking. This can be used to run a smoke test on proposed
    patches that have not been applied (yet) or to see the effect of
    reversing an already applied patch. The file format is simple:
      ...

It appears however that this option/file is not used when smoking using `tssmokeperl.pl`?

I do see references to the pfile in `bin/smokeperl.pl`: https://github.com/abeltje/Test-Smoke/blob/master/bin/smokeperl.pl#L225
and `bin/patchtree.pl` also uses it. 

(Internally `Test::Smoke::Patcher` is used to apply the patches in the pfile)

But in `tssmokeperl` and lib/Test/Smoke/App I don't see a reference to the 'pfile' config option nor to `Test::Smoke::Patcher`..
Is/was this an oversight or was this intended?

(To me it's also not 100% clear what the difference is between `bin/smokeperl.pl` and `bin/tssmokeperl.pl`, my best guess is that `bin/smokeperl.pl` is legacy and `bin/tssmokeperl.pl` is the "new" thing?)

My use case for using the pfile/patchup file was to patch the perl before smoking: to make an error message more verbose to get more useful debug output to fix it.

**Comment by abeltje** [comment]
Originally, `Test::Smoke::Patcher` was the way to get an up-to-date source-tree (download a snapshot-tarball and all the patches since the snapshot) for those that couldn't use `rsync` and had to make do with `ftp`. I believe most people use `git` as the way to sync the source-tree nowadays, so I considered having support for patching no longer necessary. Less code to maintain...
As an alternative, `git` gives one the opportunity to create a branch with changes that can be applied, and `Test::Smoke` supports smoking those branches.

I am in the middle of a huge restructure of the code where all the old scripts (without the `ts` prefix) will be replaced by a standard script that invokes the actual code in `Test::Smoke::App::<this thing>`. In this restructure, the options for the programme and the config share the same definition. Most of this restructure is done, I am now reinventing the configuration-manager `tsconfigsmoke.pl` as the last step.

If we find the patch stuff too important to drop, I'll reinstate it, the code is already there it just needs a new coat...

**Comment by abeltje** [comment]
I'm closing this issue.
